version: "3.8"
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  app:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password @host.docker.internal:5432/t3shipyard
      - NODE_ENV=production

volumes:
  caddy_data:
  caddy_config:
